### ISSUE TITLE
日志 一旦开始输入 warning和info都会出现这个日志

### ISSUE THREAD

**Issue by qiao-summer** [scomper/Rime#13]
E0208 15:20:20.874002 245222912 charset_filter.cc:106] charset parameter is unsupported by basic charset_filter

**Comment by scomper** [comment]
作者的答复是 自动构建版本没有集成librime插件

https://github.com/rime/squirrel/issues/501#issuecomment-772109790

**Comment by qiao-summer** [comment]
> 作者的答复是 自动构建版本没有集成librime插件
> 
> [rime/squirrel#501 (comment)](https://github.com/rime/squirrel/issues/501#issuecomment-772109790)

意思是我要自己打包构建吗？

**Comment by QiangF** [comment]
就一个插件，感觉原作者没必要单独搞个插件吧？

**Comment by QiangF** [comment]
这里也许相关 https://github.com/rime/librime/issues/436
