### ISSUE TITLE
部分 emoji 在 MacOS 上乱码

### ISSUE THREAD

**Issue by icefed** [scomper/Rime#14]
<img width="264" alt="image" src="https://user-images.githubusercontent.com/3964419/131625405-cb552f4e-cf87-44ed-ba76-63b0820d72b4.png">

这两个文件内的 emoji 很多会显示乱码。在 web 上看是乱码的，通过输入法输出也是乱码的。
emoji_category.txt
emoji_word.txt

**Comment by tshu-w** [comment]
感觉可能是你那问题，我这边输入或者 web 查看都正常

<img width="387" alt="Screen Shot 2021-09-01 at 16 59 45" src="https://user-images.githubusercontent.com/13161779/131643249-301fedb0-9449-48b4-bf5c-a0829a033ab9.png">
<img width="429" alt="Screen Shot 2021-09-01 at 16 58 52" src="https://user-images.githubusercontent.com/13161779/131643270-14ecd500-3f1b-4815-a017-33f18f468f38.png">

macOS 11.5.2

**Comment by icefed** [comment]
MacOS 10.15.7
换成上一个版本 Unicode 12.0 正常了
