### ISSUE TITLE
如果开启了模糊音，建议也关掉拼写纠错

### ISSUE THREAD

**Issue by fireyy** [scomper/Rime#15]
https://github.com/scomper/Rime/blob/d08a240f7366390289863653ad71e27c2c4f3eef/luna_pinyin_simp.custom.yaml#L59

开启效果
<img width="495" alt="开启效果" src="https://user-images.githubusercontent.com/66291/217699746-7647b76b-7dfb-45f6-bf2a-4ad2b74286a8.png">

关闭后效果
<img width="504" alt="关闭后效果" src="https://user-images.githubusercontent.com/66291/217699801-0c605ed3-fe5a-47ad-b813-d863e46837ae.png">

**Comment by scomper** [comment]
已更新
