### ISSUE TITLE
外观主题 system_blue 问题

### ISSUE THREAD

**Issue by ghost** [scomper/Rime#8]
感谢 @scomper 制作这个配置包！

有个问题请教：图1中蓝色边框距离最外面边框的距离能调的小一点吗？像图2一样。谢谢。

![image](https://user-images.githubusercontent.com/16677745/71541542-93842b80-2995-11ea-9f0a-d12b76ef987f.png)
【图1】鼠须管拼音输入

![image](https://user-images.githubusercontent.com/16677745/71541541-90893b00-2995-11ea-8756-33ef732e334a.png)
【图2】macOS 10.14 自带拼音输入

**Comment by scomper** [comment]
最新版是不留白边的，另外没有办法在配置中调整这个边距。

**Comment by ghost** [comment]
@scomper 您說的最新版是？
